use_frameworks!

platform :ios, '9.0'

target 'CocoaDownloader_Example' do
  pod 'CocoaDownloader', :path => '../'

  target 'CocoaDownloader_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
